java_plugin(
    name = "CaptureReturnValueofReadPlugin",
    srcs = ["CaptureReturnValueofRead.java"],
    deps = [
        "//third_party/java/auto_service",
        "@error_prone//jar"
    ],
)

java_library(
    name = "CustomPluginTests",
    srcs = ["CompliantTest1.java", 
    "NonCompliantTest1.java"],
)
