java_plugin(
    name = "UnsanitizedUntrustedDataPassedCheckPlugin",
    srcs = ["UnsanitizedUntrustedDataPassedCheckk.java"],
    deps = [
        "//third_party/java/auto_service",
        "@error_prone//jar"
    ],
)

java_library(
    name = "CustomPluginTests",
    srcs = ["SQLInjectionTest.java", 
    "XMLInjectionTest.java"],
)
